-- MySQL Script generated by MySQL Workbench
-- Thu Apr 30 07:48:14 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema phoneshop_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema phoneshop_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `phoneshop_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `phoneshop_db` ;

-- -----------------------------------------------------
-- Table `phoneshop_db`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phoneshop_db`.`roles` (
  `role_id` BIGINT NOT NULL AUTO_INCREMENT,
  `name_role` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `phoneshop_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phoneshop_db`.`users` (
  `dtype` VARCHAR(31) NOT NULL,
  `user_id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `email` VARCHAR(100) NOT NULL,
  `full_name` VARCHAR(100) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `is_active` BIT(1) NULL DEFAULT NULL,
  `phone` VARCHAR(15) NULL DEFAULT NULL,
  `hire_date` DATETIME(6) NULL DEFAULT NULL,
  `salary` DECIMAL(38,2) NULL DEFAULT NULL,
  `role_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `UK6dotkott2kjsp8vw4d0m25fb7` (`email` ASC) VISIBLE,
  INDEX `FKp56c1712k691lhsyewcssf40f` (`role_id` ASC) VISIBLE,
  CONSTRAINT `FKp56c1712k691lhsyewcssf40f`
    FOREIGN KEY (`role_id`)
    REFERENCES `phoneshop_db`.`roles` (`role_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `phoneshop_db`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phoneshop_db`.`address` (
  `address_id` BIGINT NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `district` VARCHAR(255) NULL DEFAULT NULL,
  `is_default` BIT(1) NULL DEFAULT NULL,
  `phone` VARCHAR(255) NULL DEFAULT NULL,
  `street` VARCHAR(255) NULL DEFAULT NULL,
  `ward` VARCHAR(255) NULL DEFAULT NULL,
  `user_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`address_id`),
  INDEX `FK6i66ijb8twgcqtetl8eeeed6v` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK6i66ijb8twgcqtetl8eeeed6v`
    FOREIGN KEY (`user_id`)
    REFERENCES `phoneshop_db`.`users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `phoneshop_db`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phoneshop_db`.`categories` (
  `category_id` BIGINT NOT NULL AUTO_INCREMENT,
  `is_active` BIT(1) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `slug` VARCHAR(255) NULL DEFAULT NULL,
  `parent_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`category_id`),
  INDEX `FKsaok720gsu4u2wrgbk10b5n8d` (`parent_id` ASC) VISIBLE,
  CONSTRAINT `FKsaok720gsu4u2wrgbk10b5n8d`
    FOREIGN KEY (`parent_id`)
    REFERENCES `phoneshop_db`.`categories` (`category_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `phoneshop_db`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phoneshop_db`.`products` (
  `product_id` BIGINT NOT NULL AUTO_INCREMENT,
  `brand` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `status` ENUM('ACTIVE', 'INACTIVE') NULL DEFAULT NULL,
  `category_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`product_id`),
  INDEX `FKog2rp4qthbtt2lfyhfo32lsw9` (`category_id` ASC) VISIBLE,
  CONSTRAINT `FKog2rp4qthbtt2lfyhfo32lsw9`
    FOREIGN KEY (`category_id`)
    REFERENCES `phoneshop_db`.`categories` (`category_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `phoneshop_db`.`product_variants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phoneshop_db`.`product_variants` (
  `variant_id` BIGINT NOT NULL AUTO_INCREMENT,
  `import_price` DECIMAL(38,2) NULL DEFAULT NULL,
  `price` DECIMAL(38,2) NULL DEFAULT NULL,
  `sku` VARCHAR(255) NULL DEFAULT NULL,
  `stock_qty` INT NULL DEFAULT NULL,
  `storage_gb` INT NULL DEFAULT NULL,
  `product_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`variant_id`),
  INDEX `FKosqitn4s405cynmhb87lkvuau` (`product_id` ASC) VISIBLE,
  CONSTRAINT `FKosqitn4s405cynmhb87lkvuau`
    FOREIGN KEY (`product_id`)
    REFERENCES `phoneshop_db`.`products` (`product_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `phoneshop_db`.`carts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phoneshop_db`.`carts` (
  `cart_id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `user_id` BIGINT NOT NULL,
  PRIMARY KEY (`cart_id`),
  UNIQUE INDEX `UK64t7ox312pqal3p7fg9o503c2` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FKb5o626f86h46m4s7ms6ginnop`
    FOREIGN KEY (`user_id`)
    REFERENCES `phoneshop_db`.`users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `phoneshop_db`.`cart_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phoneshop_db`.`cart_items` (
  `cart_item_id` BIGINT NOT NULL AUTO_INCREMENT,
  `added_at` DATETIME(6) NULL DEFAULT NULL,
  `product_name` VARCHAR(255) NOT NULL,
  `quantity` INT NOT NULL,
  `subtotal` DECIMAL(19,2) NOT NULL,
  `unit_price` DECIMAL(38,2) NOT NULL,
  `cart_id` BIGINT NOT NULL,
  `variant_id` BIGINT NOT NULL,
  PRIMARY KEY (`cart_item_id`),
  INDEX `FKpcttvuq4mxppo8sxggjtn5i2c` (`cart_id` ASC) VISIBLE,
  INDEX `FK5yyw1o0dor9gmxfra1dqvn4qa` (`variant_id` ASC) VISIBLE,
  CONSTRAINT `FK5yyw1o0dor9gmxfra1dqvn4qa`
    FOREIGN KEY (`variant_id`)
    REFERENCES `phoneshop_db`.`product_variants` (`variant_id`),
  CONSTRAINT `FKpcttvuq4mxppo8sxggjtn5i2c`
    FOREIGN KEY (`cart_id`)
    REFERENCES `phoneshop_db`.`carts` (`cart_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `phoneshop_db`.`feedback`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phoneshop_db`.`feedback` (
  `feedback_id` BIGINT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(2000) NOT NULL,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `resolution` VARCHAR(2000) NULL DEFAULT NULL,
  `resolved_at` DATETIME(6) NULL DEFAULT NULL,
  `status` ENUM('IN_PROGRESS', 'PENDING', 'RESOLVED') NOT NULL,
  `customer_id` BIGINT NOT NULL,
  `employee_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`feedback_id`),
  INDEX `FKihnjta1253kjyigmt2vnqbg6b` (`customer_id` ASC) VISIBLE,
  INDEX `FKrjcbndt8e6dx63ap4jv6be0ho` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `FKihnjta1253kjyigmt2vnqbg6b`
    FOREIGN KEY (`customer_id`)
    REFERENCES `phoneshop_db`.`users` (`user_id`),
  CONSTRAINT `FKrjcbndt8e6dx63ap4jv6be0ho`
    FOREIGN KEY (`employee_id`)
    REFERENCES `phoneshop_db`.`users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `phoneshop_db`.`vouchers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phoneshop_db`.`vouchers` (
  `voucher_id` BIGINT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(50) NOT NULL,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `discount_type` ENUM('FIXED', 'PERCENT') NOT NULL,
  `discount_value` DECIMAL(19,2) NOT NULL,
  `end_at` DATETIME(6) NULL DEFAULT NULL,
  `is_active` BIT(1) NOT NULL,
  `max_discount_amount` DECIMAL(19,2) NULL DEFAULT NULL,
  `min_order_amount` DECIMAL(19,2) NULL DEFAULT NULL,
  `remaining_quantity` INT NULL DEFAULT NULL,
  `start_at` DATETIME(6) NULL DEFAULT NULL,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  PRIMARY KEY (`voucher_id`),
  UNIQUE INDEX `UK30ftp2biebbvpik8e49wlmady` (`code` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `phoneshop_db`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phoneshop_db`.`orders` (
  `order_id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `discount_amount` DECIMAL(19,2) NOT NULL,
  `order_code` VARCHAR(40) NOT NULL,
  `payment_method` ENUM('COD', 'VN_PAY') NOT NULL,
  `shipping_address` VARCHAR(255) NOT NULL,
  `shipping_city` VARCHAR(100) NOT NULL,
  `shipping_district` VARCHAR(100) NULL DEFAULT NULL,
  `shipping_fee` DECIMAL(19,2) NOT NULL,
  `shipping_name` VARCHAR(100) NOT NULL,
  `shipping_phone` VARCHAR(20) NOT NULL,
  `shipping_ward` VARCHAR(100) NULL DEFAULT NULL,
  `status` ENUM('CANCELLED', 'CONFIRMED', 'DELIVERED', 'PACKING', 'PENDING', 'SHIPPING') NOT NULL,
  `total_amount` DECIMAL(19,2) NOT NULL,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `user_id` BIGINT NOT NULL,
  `voucher_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`order_id`),
  UNIQUE INDEX `UKdhk2umg8ijjkg4njg6891trit` (`order_code` ASC) VISIBLE,
  INDEX `FK32ql8ubntj5uh44ph9659tiih` (`user_id` ASC) VISIBLE,
  INDEX `FKdimvsocblb17f45ikjr6xn1wj` (`voucher_id` ASC) VISIBLE,
  CONSTRAINT `FK32ql8ubntj5uh44ph9659tiih`
    FOREIGN KEY (`user_id`)
    REFERENCES `phoneshop_db`.`users` (`user_id`),
  CONSTRAINT `FKdimvsocblb17f45ikjr6xn1wj`
    FOREIGN KEY (`voucher_id`)
    REFERENCES `phoneshop_db`.`vouchers` (`voucher_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `phoneshop_db`.`order_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phoneshop_db`.`order_items` (
  `order_item_id` BIGINT NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(255) NOT NULL,
  `quantity` INT NOT NULL,
  `subtotal` DECIMAL(19,2) NOT NULL,
  `unit_price` DECIMAL(19,2) NOT NULL,
  `order_id` BIGINT NOT NULL,
  `variant_id` BIGINT NOT NULL,
  PRIMARY KEY (`order_item_id`),
  INDEX `FKbioxgbv59vetrxe0ejfubep1w` (`order_id` ASC) VISIBLE,
  INDEX `FKemq71edpbn9wsxnxncfn1algp` (`variant_id` ASC) VISIBLE,
  CONSTRAINT `FKbioxgbv59vetrxe0ejfubep1w`
    FOREIGN KEY (`order_id`)
    REFERENCES `phoneshop_db`.`orders` (`order_id`),
  CONSTRAINT `FKemq71edpbn9wsxnxncfn1algp`
    FOREIGN KEY (`variant_id`)
    REFERENCES `phoneshop_db`.`product_variants` (`variant_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `phoneshop_db`.`payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phoneshop_db`.`payments` (
  `payment_id` BIGINT NOT NULL AUTO_INCREMENT,
  `bank_code` VARCHAR(20) NULL DEFAULT NULL,
  `bank_transaction_no` VARCHAR(50) NULL DEFAULT NULL,
  `card_type` VARCHAR(20) NULL DEFAULT NULL,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `gateway_transaction_no` VARCHAR(50) NULL DEFAULT NULL,
  `method` ENUM('COD', 'VN_PAY') NOT NULL,
  `paid_at` DATETIME(6) NULL DEFAULT NULL,
  `pay_date` VARCHAR(20) NULL DEFAULT NULL,
  `response_code` VARCHAR(10) NULL DEFAULT NULL,
  `response_message` VARCHAR(255) NULL DEFAULT NULL,
  `status` ENUM('FAILED', 'PENDING', 'REFUNDED', 'SUCCESS') NOT NULL,
  `transaction_ref` VARCHAR(100) NULL DEFAULT NULL,
  `transaction_status` VARCHAR(10) NULL DEFAULT NULL,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `order_id` BIGINT NOT NULL,
  PRIMARY KEY (`payment_id`),
  UNIQUE INDEX `UKjwk4x78utnlycetjq9ulvm7tr` (`transaction_ref` ASC) VISIBLE,
  INDEX `idx_payments_order_id` (`order_id` ASC) VISIBLE,
  CONSTRAINT `FK81gagumt0r8y3rmudcgpbk42l`
    FOREIGN KEY (`order_id`)
    REFERENCES `phoneshop_db`.`orders` (`order_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `phoneshop_db`.`product_images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phoneshop_db`.`product_images` (
  `image_id` BIGINT NOT NULL AUTO_INCREMENT,
  `is_primary` BIT(1) NULL DEFAULT NULL,
  `url` VARCHAR(255) NULL DEFAULT NULL,
  `variant_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`image_id`),
  INDEX `FKqnqjv00ocaxfmu2k6b99ycdad` (`variant_id` ASC) VISIBLE,
  CONSTRAINT `FKqnqjv00ocaxfmu2k6b99ycdad`
    FOREIGN KEY (`variant_id`)
    REFERENCES `phoneshop_db`.`product_variants` (`variant_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `phoneshop_db`.`reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phoneshop_db`.`reviews` (
  `review_id` BIGINT NOT NULL AUTO_INCREMENT,
  `comment` VARCHAR(1000) NULL DEFAULT NULL,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `rating` INT NOT NULL,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `user_id` BIGINT NOT NULL,
  `product_id` BIGINT NOT NULL,
  PRIMARY KEY (`review_id`),
  UNIQUE INDEX `uk_review_customer_product` (`user_id` ASC, `product_id` ASC) VISIBLE,
  INDEX `FKpl51cejpw4gy5swfar8br9ngi` (`product_id` ASC) VISIBLE,
  CONSTRAINT `FKcgy7qjc1r99dp117y9en6lxye`
    FOREIGN KEY (`user_id`)
    REFERENCES `phoneshop_db`.`users` (`user_id`),
  CONSTRAINT `FKpl51cejpw4gy5swfar8br9ngi`
    FOREIGN KEY (`product_id`)
    REFERENCES `phoneshop_db`.`products` (`product_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `phoneshop_db`.`shipments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phoneshop_db`.`shipments` (
  `shipment_id` BIGINT NOT NULL AUTO_INCREMENT,
  `carrier` VARCHAR(30) NOT NULL,
  `client_order_code` VARCHAR(80) NULL DEFAULT NULL,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `expected_delivery_at` DATETIME(6) NULL DEFAULT NULL,
  `ghn_order_code` VARCHAR(80) NULL DEFAULT NULL,
  `ghn_status` VARCHAR(50) NULL DEFAULT NULL,
  `last_synced_at` DATETIME(6) NULL DEFAULT NULL,
  `raw_payload` TINYTEXT NULL DEFAULT NULL,
  `status` ENUM('CANCELLED', 'DELIVERED', 'EXCEPTION', 'IN_TRANSIT', 'PENDING', 'PICKED_UP', 'RETURNED', 'RETURNING') NOT NULL,
  `status_message` VARCHAR(255) NULL DEFAULT NULL,
  `tracking_url` VARCHAR(255) NULL DEFAULT NULL,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `order_id` BIGINT NOT NULL,
  PRIMARY KEY (`shipment_id`),
  UNIQUE INDEX `UKhrhy2yghr8dampg1jtecuekvp` (`order_id` ASC) VISIBLE,
  UNIQUE INDEX `UKb7luoy48q75rl2kdqvly6aokh` (`client_order_code` ASC) VISIBLE,
  UNIQUE INDEX `UKf133e7ar3c0sc1gc49199o205` (`ghn_order_code` ASC) VISIBLE,
  CONSTRAINT `FKrnt4wht95lxxplspltrg9681s`
    FOREIGN KEY (`order_id`)
    REFERENCES `phoneshop_db`.`orders` (`order_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `phoneshop_db`.`shipment_events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phoneshop_db`.`shipment_events` (
  `event_id` BIGINT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(500) NULL DEFAULT NULL,
  `event_type` VARCHAR(60) NULL DEFAULT NULL,
  `ghn_status` VARCHAR(60) NULL DEFAULT NULL,
  `occurred_at` DATETIME(6) NULL DEFAULT NULL,
  `raw_payload` TINYTEXT NULL DEFAULT NULL,
  `shipment_status` ENUM('CANCELLED', 'DELIVERED', 'EXCEPTION', 'IN_TRANSIT', 'PENDING', 'PICKED_UP', 'RETURNED', 'RETURNING') NULL DEFAULT NULL,
  `warehouse` VARCHAR(255) NULL DEFAULT NULL,
  `shipment_id` BIGINT NOT NULL,
  PRIMARY KEY (`event_id`),
  INDEX `FKn1kde3h6pigtoxnr7p9o6mht8` (`shipment_id` ASC) VISIBLE,
  CONSTRAINT `FKn1kde3h6pigtoxnr7p9o6mht8`
    FOREIGN KEY (`shipment_id`)
    REFERENCES `phoneshop_db`.`shipments` (`shipment_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Dữ liệu cập nhật ảnh sản phẩm (Khắc phục lỗi Unsplash)
-- -----------------------------------------------------
UPDATE `phoneshop_db`.`product_images` 
SET url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/IPhone_15_Pro_Max_Natural_Titanium.svg/800px-IPhone_15_Pro_Max_Natural_Titanium.svg.png' 
WHERE url LIKE '%1695048133142%';

UPDATE `phoneshop_db`.`product_images` 
SET url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Samsung_Galaxy_S24_Ultra.jpg/800px-Samsung_Galaxy_S24_Ultra.jpg' 
WHERE url LIKE '%1706015502695%';
